#!/bin/sh
RUN_DAEMON="no"
DESC="initializing LVM"

start() {
	if [ "$RUN_DAEMON" != "yes" ] ; then
		echo " *** $DESC disabled ***>>"
		exit 0
	fi

	echo " *** Start $DESC ***>>"
	/sbin/modprobe dm-mod
	/sbin/vgscan > /dev/null 2>&1
	/sbin/vgchange -ay > /dev/null 2>&1
}	
stop() {
	echo " *** Stop $DESC ***>>"
	/sbin/vgchange -an > /dev/null 2>&1
	/sbin/modprobe -r dm-mod 
}
restart() {
	stop
	start
}	

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

