#!/bin/sh

start() {
	echo " *** Setting Kernel parameters ***>>"
	/sbin/sysctl -p
}	
stop() {
	exit 0;	
}
restart() {
	stop
	start
}	

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

