#!/bin/sh
#
# rdate
#

DESC="set time"
TICK="10076"

start() {
	echo " *** Start $DESC ***>>"
	. /etc/config
	/sbin/adjtimex -t $TICK >/dev/null 2>&1
	echo $TZ > /etc/TZ
	case "$TIME_MODE" in 
	1)	#from ntp-server 123
	    [ $NTPSERV ] && NTP_SERVER=$NTPSERV
	    echo "ntpclient ${NTP_SERVER}"

	    ntpclient -h ${NTP_SERVER} -i 86400 -c 0 -s &  #86400 is one day
	    [ $? -eq 0 ] && {
	    sleep 1
	    echo "ntpclient: Updated local time from ${NTP_SERVER}"
	    touch /tmp/ntpclient.run
	    } || TZ=xxx+0 date ${TIME_VALUE}
	    ;;
	
	2)	#from time-server 37
	    [ $TIMESERV ] && TIME_SERVER=$TIMESERV
	    echo "rdate ${TIME_SERVER}"

	    rdate -s ${TIME_SERVER}
	    [ $? -eq 0 ] && {
	    sleep 1
	    echo "rdate: Updated local time from ${TIME_SERVER}"
	    } || TZ=xxx+0 date ${TIME_VALUE}
	    ;;
	*)	#from config
#	    TZ=xxx+0 date ${TIME_VALUE}
	    ;;
	esac
}
stop() {
	echo " *** Save time ***>>"
	httpd_cfg TIME_VALUE=`date "+%m%d%H%M%Y"`
	killall ntpclient
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

