#!/bin/sh
RUN_DAEMON="yes"
DESC="inetd Daemon"

start() {
	if [ "$RUN_DAEMON" != "yes" ] ; then
		echo " *** $DESC disabled ***>>"
		exit 0
	fi

	echo " *** Start $DESC ***>>"
	/sbin/inetd
}
stop() {
	echo " *** Stop $DESC ***>>"
	killall -9 inetd 2>/dev/null
}
restart() {
	stop
	start
}

reload() {
	echo " *** Reload inetd Daemon ***>>"
	killall -HUP inetd
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  reload)
	reload
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

