#!/bin/sh

start() {
	. /etc/config
	if [ ! -e /mnt/.no_netbios ] & [ -e /usr/bin/nmbd ] & [ ${NMB_ENABLE:=1} -eq 1 ]; then
	echo " *** Start NetBIOS ***>>"
##    codepage=`echo ${CODE_SET} | cut -d '-' -f1`
##    charset=`echo ${CODE_SET} | cut -d '-' -f2`
##	charnum=`echo ${CODE_SET} | cut -d '-' -f3`
#	/usr/sbin/nmbd -D
	nmbd -D
	fi
}
stop() {
	echo " *** Stop NetBIOS ***>>"
	killall -15 nmbd >/dev/null 2>&1
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac
exit $?
