name: C/C++ CI

on: [push]

jobs:
   build-linux:
    name: Linux build

    runs-on: ubuntu-latest
    
    steps:
       - name: List files
       run: ls
       - name: make
       run: |
        cat /Makefile
        make all
