name: C/C++ CI

on: [push]

jobs:
   build-linux:
    name: Linux build

    runs-on: ubuntu-latest
    
    steps:
    - name: make
      run: |
         ls -l
        cd /httpd_nh221
        make all
