name: C/C++ CI

on: [push,pull_request]

jobs:
   build-linux:
    name: Linux build

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: List files
      run: |
         ls
         env
      - name: make
      run: |
         cat Makefile
         make
         
