<!--#include mfexchange="1-ShowMainHtml.htm" mfexchange="1-network.htm"
mfexchange="1-system.htm" mfexchange="1-services.htm"
mfexchange="1-access.htm" mfexchange="1-p2p-main.htm"
mfexchange="1-USB.htm" mfexchange="1-packages.htm"
-->
      <td width="160">
      <table nof="LY" border="0" cellpadding="0" cellspacing="0"
 width="156">
        <tbody>
          <tr align="left" valign="top">
            <td><br>
            </td>
          </tr>
          <tr align="left" valign="top">
            <td style="height: 507px;"><br><!--size of sidebar, default:507px-->
            </td>
            <td style="width: 152px;"><!--sidebar-->
            <table id="leftBar" nof="NB_PYVPNY026" border="0"
 cellpadding="0" cellspacing="0" width="152">
              <tbody>
                <tr align="left" valign="top">
                  <td height="36" width="150"><a href="/1-ShowMainHtml.htm"><img
 id="Nav111" name="Nav1" src="/images/Bhome<!-- if="_##i:1/" -->-o<!-- /if -->.png"
 alt="Homepage" border="0" height="36" width="150"></a></td>
                </tr>
                <tr align="left" valign="top">
                  <td height="36" width="150"><a href="/1-network.htm"><img
 id="Nav2" name="Nav2" src="/images/Bnetwork<!-- if="_##i:2/" -->-o<!-- /if -->.png"
 alt="Networking" border="0" height="36" width="150"></a></td>
                </tr>
                <tr align="left" valign="top">
                  <td height="36" width="150"><a href="/1-system.htm"><img
 id="Nav3" name="Nav3" src="/images/Bsystem<!-- if="_##i:3/" -->-o<!-- /if -->.png"
 alt="System" border="0" height="36" width="150"></a></td>
                </tr>
                <tr align="left" valign="top">
                  <td height="36" width="150"><a href="/1-services.htm"><img
 id="Nav4" name="Nav4" src="/images/Bservices<!-- if="_##i:4/" -->-o<!-- /if -->.png"
 alt="Services" border="0" height="36" width="150"></a></td>
                </tr>
                <tr align="left" valign="top">
                  <td height="36" width="150"><a href="/1-access.htm"><img
 id="Nav5" name="Nav5" src="/images/Baccess<!-- if="_##i:5/" -->-o<!-- /if -->.png"
 alt="Access" border="0" height="36" width="150"></a></td>
                </tr>
                <tr align="left" valign="top">
                  <td height="36" width="150"><a href="/1-p2p-main.htm"><img
 id="Nav6" name="Nav6" src="/images/Bp2p<!-- if="_##i:6/" -->-o<!-- /if -->.png"
 alt="P2P" border="0" height="36" width="150"></a></td>
                </tr>
                <tr align="left" valign="top">
                  <td height="36" width="150"><a href="/1-USB.htm"><img
 id="Nav7" name="Nav7" src="/images/Busb<!-- if="_##i:7/" -->-o<!-- /if -->.png"
 alt="USB" border="0" height="36" width="150"></a></td>
                </tr>
                <tr align="left" valign="top">
                  <td height="36" width="150"><a href="/1-packages.htm"><img
 id="Nav8" name="Nav8" src="/images/Bpkgs<!-- if="_##i:8/" -->-o<!-- /if -->.png"
 alt="Packages" border="0" height="36" width="150"></a></td>
                </tr>
<!-- if="_##helper:" -->
                <tr>
                <td height="36" width="150"><hr><div style="text-align:center;">
<a href="javascript:help_popUp();">HELP</a></div>
                </td>
                </tr>
<!-- /if -->
<!-- if="_etc_save:1/" -->
                <tr>
                <td height="36" width="150"><hr><div style="text-align:center;">
<a href="/etc_save.cgi">save</a> /etc dir</div>
                </td>
                </tr>
<!-- CGI: etc_save.cgi
    write_par "_etc_save:0";
    my_system "/etc/save_config.sh";
//	my_system "/etc/btn_config.sh rstbtn_short" ;
END_CGI -->
<!-- /if -->
              </tbody>
            </table>
            </td>
          </tr>
        </tbody>
      </table>
      </td>	<!--end of sidebar-->
      <td> <br>
